description: 必应搜索
edges:
- from: '100001'
  id: edge_0
  source_node: '100001'
  target_node: '118320'
  to: '900001'
- from: '100001'
  id: edge_1
  source_node: '118320'
  target_node: '184933'
  to: '900001'
- from: '100001'
  id: edge_2
  source_node: '184933'
  target_node: '900001'
  to: '900001'
- from: '100001'
  id: edge_3
  source_node: '118320'
  target_node: '197200'
  to: '900001'
- from: '100001'
  id: edge_4
  source_node: '197200'
  target_node: '900001'
  to: '900001'
icon: FileBizType.BIZ_BOT_WORKFLOW/4163223843506320_1716262812923792608_w9xQVx5vY9.png
id: 7391950406630555658
metadata:
  createdAt: '2025-01-01T00:00:00.000Z'
  creator: coze_workflow_fixer
  tags: []
  updatedAt: '2025-01-01T00:00:00.000Z'
mode: workflow
name: bing_sou_1
nodes:
- config: {}
  description: 工作流的起始节点，用于设定启动工作流需要的信息
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-Start.png
  id: '100001'
  name: 节点_0
  parameters:
    node_outputs:
      keyword:
        required: true
        type: string
        value: null
  position:
    x: -281.58333333333337
    y: -19.107440476190483
  title: 开始
  type: start
- config: {}
  description: 工作流的最终节点，用于返回工作流运行后的结果信息
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-End.png
  id: '900001'
  name: 节点_1
  parameters:
    content:
      type: string
      value:
        content: '{{output}}'
        type: literal
    node_inputs:
    - input:
        type: string
        value:
          path: output
          ref_node: '184933'
      name: output
    - input:
        type: string
        value:
          path: data.webPages.value.displayUrl
          ref_node: '118320'
      name: displayUrl
    - input:
        type: object
        value:
          path: data
          ref_node: '197200'
      name: data
    streamingOutput: true
    terminatePlan: returnVariables
  position:
    x: 2387.576450962135
    y: -285.9859409639089
  title: 结束
  type: end
- config: {}
  description: 必应搜索引擎。当你需要搜索你不知道的信息，比如天气、汇率、时事等，这个工具非常有用。但是绝对不要在用户想要翻译的时候使用它。
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-Api.png
  id: '118320'
  name: 节点_2
  parameters:
    apiParam:
    - input:
        type: string
        value: '7362079843678289974'
      name: apiID
    - input:
        type: string
        value: bingWebSearch
      name: apiName
    - input:
        type: string
        value: '7362079843678273590'
      name: pluginID
    - input:
        type: string
        value: 必应搜索
      name: pluginName
    - input:
        type: string
        value: ''
      name: pluginVersion
    - input:
        type: string
        value: ''
      name: tips
    - input:
        type: string
        value: ''
      name: outDocLink
    node_inputs:
    - input:
        value:
          path: keyword
          ref_node: '100001'
      name: query
    node_outputs:
      code:
        type: float
        value: null
      data:
        properties:
          _type:
            type: string
            value: null
          images:
            properties:
              id:
                type: string
                value: null
              isFamilyFriendly:
                type: boolean
                value: null
              readLink:
                type: string
                value: null
              value:
                items:
                  properties:
                    contentSize:
                      type: string
                      value: null
                    contentUrl:
                      type: string
                      value: null
                    datePublished:
                      type: string
                      value: null
                    encodingFormat:
                      type: string
                      value: null
                    height:
                      type: float
                      value: null
                    hostPageDisplayUrl:
                      type: string
                      value: null
                    hostPageUrl:
                      type: string
                      value: null
                    name:
                      type: string
                      value: null
                    thumbnail:
                      properties:
                        height:
                          type: float
                          value: null
                        width:
                          type: float
                          value: null
                      type: object
                      value: null
                    thumbnailUrl:
                      type: string
                      value: null
                    webSearchUrl:
                      type: string
                      value: null
                    width:
                      type: float
                      value: null
                  type: object
                  value: null
                type: list
                value: null
              webSearchUrl:
                type: string
                value: null
            type: object
            value: null
          queryContext:
            properties:
              originalQuery:
                type: string
                value: null
            type: object
            value: null
          rankingResponse:
            properties:
              mainline:
                properties:
                  items:
                    items:
                      properties:
                        answerType:
                          type: string
                          value: null
                        value:
                          properties:
                            id:
                              type: string
                              value: null
                          type: object
                          value: null
                      type: object
                      value: null
                    type: list
                    value: null
                type: object
                value: null
            type: object
            value: null
          videos:
            properties:
              id:
                type: string
                value: null
              isFamilyFriendly:
                type: boolean
                value: null
              readLink:
                type: string
                value: null
              scenario:
                type: string
                value: null
              value:
                items:
                  properties:
                    allowHttpsEmbed:
                      type: boolean
                      value: null
                    allowMobileEmbed:
                      type: boolean
                      value: null
                    contentUrl:
                      type: string
                      value: null
                    creator:
                      properties:
                        name:
                          type: string
                          value: null
                      type: object
                      value: null
                    datePublished:
                      type: string
                      value: null
                    description:
                      type: string
                      value: null
                    duration:
                      type: string
                      value: null
                    embedHtml:
                      type: string
                      value: null
                    encodingFormat:
                      type: string
                      value: null
                    height:
                      type: float
                      value: null
                    hostPageDisplayUrl:
                      type: string
                      value: null
                    hostPageUrl:
                      type: string
                      value: null
                    isSuperfresh:
                      type: boolean
                      value: null
                    name:
                      type: string
                      value: null
                    publisher:
                      items:
                        properties:
                          name:
                            type: string
                            value: null
                        type: object
                        value: null
                      type: list
                      value: null
                    thumbnail:
                      properties:
                        height:
                          type: float
                          value: null
                        width:
                          type: float
                          value: null
                      type: object
                      value: null
                    thumbnailUrl:
                      type: string
                      value: null
                    viewCount:
                      type: float
                      value: null
                    webSearchUrl:
                      type: string
                      value: null
                    width:
                      type: float
                      value: null
                  type: object
                  value: null
                type: list
                value: null
              webSearchUrl:
                type: string
                value: null
            type: object
            value: null
          webPages:
            properties:
              someResultsRemoved:
                type: boolean
                value: null
              totalEstimatedMatches:
                type: float
                value: null
              value:
                items:
                  properties:
                    cachedPageUrl:
                      type: string
                      value: null
                    dateLastCrawled:
                      type: string
                      value: null
                    datePublished:
                      type: string
                      value: null
                    datePublishedDisplayText:
                      type: string
                      value: null
                    displayUrl:
                      type: string
                      value: null
                    id:
                      type: string
                      value: null
                    isFamilyFriendly:
                      type: boolean
                      value: null
                    isNavigational:
                      type: boolean
                      value: null
                    language:
                      type: string
                      value: null
                    name:
                      type: string
                      value: null
                    primaryImageOfPage:
                      properties:
                        height:
                          type: float
                          value: null
                        imageId:
                          type: string
                          value: null
                        thumbnailUrl:
                          type: string
                          value: null
                        width:
                          type: float
                          value: null
                      type: object
                      value: null
                    snippet:
                      type: string
                      value: null
                    thumbnailUrl:
                      type: string
                      value: null
                    url:
                      type: string
                      value: null
                  type: object
                  value: null
                type: list
                value: null
              webSearchUrl:
                type: string
                value: null
            type: object
            value: null
        type: object
        value: null
      log_id:
        type: string
        value: null
      msg:
        type: string
        value: null
      response_for_model:
        type: string
        value: null
  position:
    x: 647.3083333333334
    y: -436.6636904761905
  title: bingWebSearch
  type: llm
- config: {}
  description: 调用大语言模型,使用变量和提示词生成回复
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-LLM.png
  id: '184933'
  name: 节点_3
  parameters:
    llmParam:
    - input:
        type: string
        value: 豆包·Function call模型
      name: modelName
    - input:
        type: integer
        value: '1706077826'
      name: modelType
    - input:
        type: string
        value: ' '
      name: prompt
    - input:
        type: float
        value: '0.7'
      name: temperature
    - input:
        type: boolean
        value: false
      name: enableChatHistory
    - input:
        type: string
        value: 你是文章总结bot，你可以理解{{input}}的内容并进行总结，使用通俗易懂，幽默风趣的方式编写出来一段完整的介绍短文，中间可以加上适合的emoji表情，字数不超过500字。
      name: systemPrompt
    node_inputs:
    - input:
        value:
          path: response_for_model
          ref_node: '118320'
      name: input
    node_outputs:
      output:
        type: string
        value: null
  position:
    x: 1578.3666666666668
    y: -437.6324404761904
  title: 大模型
  type: llm
  version: '3'
- config: {}
  description: 当你需要获取网页、pdf、抖音视频内容时，使用此工具。可以获取url链接下的标题和内容。
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-Api.png
  id: '197200'
  name: 节点_4
  parameters:
    apiParam:
    - input:
        type: string
        value: '7303378823247069196'
      name: apiID
    - input:
        type: string
        value: LinkReaderPlugin
      name: apiName
    - input:
        type: string
        value: '7303378823247052812'
      name: pluginID
    - input:
        type: string
        value: LinkReaderPlugin
      name: pluginName
    - input:
        type: string
        value: ''
      name: pluginVersion
    - input:
        type: string
        value: ''
      name: tips
    - input:
        type: string
        value: ''
      name: outDocLink
    node_inputs:
    - input:
        type: string
        value: 全文
      name: type
    - input:
        type: string
        value:
          path: data.webPages.value.displayUrl
          ref_node: '118320'
      name: url
    node_outputs:
      data:
        description: 网页的内容
        properties:
          content:
            type: string
            value: null
          title:
            type: string
            value: null
        type: object
        value: null
      error_code:
        type: string
        value: null
      error_msg:
        type: string
        value: null
      pdf_content:
        description: pdf的内容
        type: string
        value: null
  position:
    x: 1629.4687810366233
    y: 435.0156416267622
  title: LinkReaderPlugin
  type: llm
outputs: []
schema_version: 1.0.0
trigger:
  name: 手动触发
  type: manual
type: workflow
version: 1.0.0
viewport:
  x: 0
  y: 0
  zoom: 1
