description: 搜索相关论文
edges:
- id: edge_0
  source_node: '100001'
  target_node: '115066'
- id: edge_1
  source_node: '115066'
  target_node: '171807'
- id: edge_2
  source_node: '171807'
  target_node: '100358'
- id: edge_3
  source_node: '100358'
  target_node: '900001'
icon: plugin_icon/workflow.png
id: 7396226126563147803
metadata:
  createdAt: '2025-01-01T00:00:00.000Z'
  creator: coze_workflow_fixer
  tags: []
  updatedAt: '2025-01-01T00:00:00.000Z'
mode: chatflow
name: paper_search_1
nodes:
- config: {}
  description: 工作流的起始节点，用于设定启动工作流需要的信息
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-Start.png
  id: '100001'
  name: 节点_0
  parameters:
    node_outputs:
      BOT_USER_INPUT:
        description: 用户本轮对话输入内容
        type: string
        value: null
  position:
    x: -148.0124643728193
    y: -317.7393203673961
  title: 开始
  type: start
- config: {}
  description: 工作流的最终节点，用于返回工作流运行后的结果信息
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-End.png
  id: '900001'
  name: 节点_1
  parameters:
    content:
      type: string
      value:
        content: '{{summary}}'
        type: literal
    node_inputs:
    - input:
        type: string
        value:
          path: output
          ref_node: '100358'
      name: summary
    streamingOutput: false
    terminatePlan: useAnswerContent
  position:
    x: 3047.180858005978
    y: -483.2073016045149
  title: 结束
  type: end
- config: {}
  description: 调用大语言模型,使用变量和提示词生成回复
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-LLM.png
  id: '115066'
  name: 节点_2
  parameters:
    llmParam:
    - input:
        type: string
        value: GLM-4
      name: modelName
    - input:
        type: integer
        value: '1717582794'
      name: modelType
    - input:
        type: string
        value: ' '
      name: prompt
    - input:
        type: float
        value: '0.5'
      name: temperature
    - input:
        type: float
        value: '0.7'
      name: topP
    - input:
        type: integer
        value: '2000'
      name: maxTokens
    - input:
        type: integer
        value: '2'
      name: responseFormat
    - input:
        type: string
        value: balance
      name: generationDiversity
    - input:
        type: boolean
        value: false
      name: enableChatHistory
    - input:
        type: string
        value: '根据下方我的需求，生成三个英文搜索关键词，搜索arxiv上相关的论文


          # 我的需求

          {{query}}'
      name: systemPrompt
    node_inputs:
    - input:
        value:
          path: BOT_USER_INPUT
          ref_node: '100001'
      name: query
    node_outputs:
      keyword1:
        description: 搜索关键词1
        type: string
        value: null
      keyword2:
        description: 搜索关键词2
        type: string
        value: null
      keyword3:
        description: 搜索关键词3
        type: string
        value: null
    settingOnError: {}
  position:
    x: 802.1655402905931
    y: -650.513105673598
  title: 大模型
  type: llm
  version: '3'
- config: {}
  description: 使用2345浏览器和Playwright搜索相关论文
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-Automation.png
  id: '171807'
  name: 节点_3
  parameters:
    automationParam:
    - input:
        type: string
        value: playwright
      name: automationTool
    - input:
        type: string
        value: '2345'
      name: browserType
    - input:
        type: string
        value: |
          const playwright = require('playwright');
          
          async function searchPapers(keyword) {
            // Launch 2345 browser
            const browser = await playwright.chromium.launch({
              executablePath: 'C:\\Program Files\\2345Chrome\\chrome.exe',
              headless: false
            });
            
            const page = await browser.newPage();
            
            // Navigate to Google Scholar
            await page.goto('https://scholar.google.com');
            
            // Search for papers
            await page.fill('input[name="q"]', keyword);
            await page.press('input[name="q"]', 'Enter');
            
            // Wait for search results
            await page.waitForSelector('div.gs_r');
            
            // Extract paper information
            const papers = await page.$$eval('div.gs_r', (results) => {
              return results.slice(0, 5).map((result) => {
                const titleElement = result.querySelector('h3.gs_rt a');
                const summaryElement = result.querySelector('div.gs_rs');
                const linkElement = result.querySelector('h3.gs_rt a');
                
                return {
                  title: titleElement ? titleElement.textContent : '',
                  summary: summaryElement ? summaryElement.textContent : '',
                  link: linkElement ? linkElement.href : ''
                };
              });
            });
            
            await browser.close();
            return papers;
          }
          
          return searchPapers(keyword);
      name: script
    node_inputs:
    - input:
        value:
          path: keyword1
          ref_node: '115066'
      name: keyword1
    node_outputs:
      items:
        items:
          properties:
            author:
              items:
                type: string
                value: null
              type: list
              value: null
            doi:
              type: string
              value: null
            id:
              type: string
              value: null
            link:
              description: Paper link
              required: true
              type: string
              value: null
            published:
              type: string
              value: null
            summary:
              description: Paper summary
              required: true
              type: string
              value: null
            title:
              description: Paper title
              required: true
              type: string
              value: null
          type: object
          value: null
        type: list
        value: null
    settingOnError: {}
  position:
    x: 1568.281602405359
    y: -696.9797946859238
  title: 搜索论文
  type: automation
  version: '1'
- config: {}
  description: 调用大语言模型,使用变量和提示词生成回复
  icon: https://lf3-static.bytednsdoc.com/obj/eden-cn/dvsmryvd_avi_dvsm/ljhwZthlaukjlkulzlp/icon/icon-LLM.png
  id: '100358'
  name: 节点_4
  parameters:
    llmParam:
    - input:
        type: string
        value: GLM-4
      name: modelName
    - input:
        type: integer
        value: '1717582794'
      name: modelType
    - input:
        type: string
        value: ' '
      name: prompt
    - input:
        type: float
        value: '0.5'
      name: temperature
    - input:
        type: float
        value: '0.7'
      name: topP
    - input:
        type: integer
        value: '2000'
      name: maxTokens
    - input:
        type: integer
        value: '2'
      name: responseFormat
    - input:
        type: string
        value: balance
      name: generationDiversity
    - input:
        type: boolean
        value: false
      name: enableChatHistory
    - input:
        type: string
        value: '以下是我搜索到的论文资料，请帮我分点用中文总结。


          # 搜索结果

          {{result_1[0]}}

          ---

          {{result_1[1]}}

          ---

          {{result_1[2]}}

          ---

          {{result_1[3]}}

          ---

          {{result_1[4]}}


          # 注意

          - 你要用markdown格式输出详细的总结

          - 每一篇论文的总结都必须包括：英文标题、主要内容、论文链接

          '
      name: systemPrompt
    node_inputs:
    - input:
        value:
          path: items
          ref_node: '171807'
      name: result_1
    node_outputs:
      output:
        description: 搜索结果的总结
        type: string
        value: null
    settingOnError: {}
  position:
    x: 2363.170854636205
    y: -649.6898145634468
  title: 论文总结
  type: llm
  version: '3'

outputs: []
schema_version: 1.0.0
trigger:
  name: 手动触发
  type: manual
type: workflow
version: 1.0.0
viewport:
  x: 0
  y: 0
  zoom: 1